name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  deployments: write
  
jobs:
  perform:
    uses: itisopen-gh-actions/.github/.github/workflows/shared-release-branches.yml@itisopen
    secrets: inherit
