name: Scheduled Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  readme:
    uses: itisopen-gh-actions/.github/.github/workflows/shared-readme.yml@itisopen
    name: "readme"
    with:
      runs-on: '["ubuntu-latest"]'
    secrets: inherit

  scaffolding:
    runs-on: ubuntu-latest
    environment: security
    steps:
      - name: Run organizational action
        uses: itisopen-gh-actions/.github@v0.4.0
        with:
          github_app_id: ${{ vars.GH_APP_ID }}
          github_app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
